name: Update package versions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
      
jobs:
  update_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scoop update
        shell: pwsh
        run: |
          $res = ./bin/checkver.ps1 -App * -Dir .\bucket -Update
          $res

          #Fails when there are uncommitted changes
          git diff-index --quiet HEAD

          if(-not $?)
          {
            #THERE ARE CHANGES
            git stage .
            git commit -m "chore(packages): auto update of packages" -m "$res"
            git push
          } else
          {
            echo "No packages required updates"
          }
